server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: your_lavalink_password
    sources:
      youtube: false


    bufferDurationMs: 400
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0"
      repository: "https://maven.lavalink.dev/releases"


plugins:
  lavasrc:
    providers:
      - "spsearch:%QUERY%"
      - "amsearch:%QUERY%"
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
      countryCode: "US"
    applemusic:
      countryCode: "US"
    deezer:
      masterKey: "${DEEZER_MASTER_KEY:}"
      countryCode: "US"
  lavalyrics:
    sources:
      - spotify
      - applemusic
      - youtube
